import type { Herramienta } from "./tipos";

/**
 * Las 34 herramientas del sitio, en 6 categorías. `estado: "pendiente"` = todavía no existe su página (su URL responde 404 y
 * no se enlaza desde ningún sitio). Para publicar una: crear su página, cambiar el estado a "publicada" y completar
 * fechaPublicacion, fechaActualizacion y `pagina` (ver docs/COMO-AGREGAR-UNA-HERRAMIENTA.md).
 */
export const HERRAMIENTAS: Herramienta[] = [
  // ───────────── Carrera y empleo (las rutas de trabajo «empleabilidad-y-trabajo/…» se publican aquí) ─────────────
  {
    slug: "crear-cv-ats-formato-harvard",
    categoria: "carrera-y-empleo",
    titulo: "Crear CV Harvard compatible con ATS con IA (Word gratis)",
    descripcionCorta: "Crea tu hoja de vida en formato Harvard y descárgala en Word, lista para los filtros ATS.",
    estado: "publicada",
    lote: 1,
    fechaPublicacion: "2026-09-25",
    fechaActualizacion: "2026-09-25",
    relacionadas: ["optimizar-cv", "analizar-oferta-laboral", "preparar-entrevista-de-trabajo"],
    pagina: {
      h1: "Crea tu CV desde cero en formato Harvard y que pase los filtros ATS",
      tituloCorto: "Crear un CV en formato Harvard que pase filtros ATS",
      metaTitulo: "CV formato Harvard para ATS: crea y descarga en Word",
      descripcion: "Llena tus datos, copia el prompt y descarga tu hoja de vida en Word con formato Harvard, lista para filtros ATS. Gratis, sin registro y con ejemplos.",
      resumen: "Llena tus datos, copia el prompt que se arma solo y descarga tu hoja de vida en Word, con formato Harvard y pensada para los filtros ATS.",
      tipo: "cv-ats",
      tiempo: "10–15 min",
      tiempoLectura: "20 min",
      etiquetaBoton: "Abrir",
      etiquetas: ["Descarga en Word"],
      secciones: [
        { id: "como-funciona", titulo: "Cómo funciona la herramienta" },
        { id: "ats", titulo: "Qué es un ATS y cómo filtra hojas de vida" },
        { id: "harvard", titulo: "El formato Harvard" },
        { id: "errores", titulo: "Errores que hacen fallar a un ATS" },
        { id: "prompt", titulo: "Cómo está hecho el prompt" },
        { id: "vinetas", titulo: "Viñetas con verbos de acción" },
        { id: "oferta", titulo: "Cómo adaptar tu CV a una oferta" },
        { id: "perfiles", titulo: "Perfil profesional por nivel" },
        { id: "ejemplo", titulo: "Ejemplo de resultado" },
        { id: "checklist", titulo: "Lista de revisión" },
        { id: "limites", titulo: "Límites y verificación" },
        { id: "preguntas", titulo: "Preguntas frecuentes" },
      ],
    },
  },
  {
    slug: "optimizar-cv",
    categoria: "carrera-y-empleo",
    titulo: "Optimizar tu CV con IA para una oferta (sin inventar nada)",
    descripcionCorta: "Ajusta tu hoja de vida a una oferta concreta sin inventar experiencia ni cifras.",
    estado: "publicada",
    lote: 1,
    fechaPublicacion: "2026-09-25",
    fechaActualizacion: "2026-09-25",
    relacionadas: ["crear-cv-ats-formato-harvard", "analizar-oferta-laboral", "preparar-entrevista-de-trabajo"],
    pagina: {
      h1: "Optimiza tu CV actual para una oferta concreta",
      tituloCorto: "Optimizar tu CV con IA para una oferta",
      metaTitulo: "Optimizar tu CV con IA para una oferta (sin inventar nada)",
      descripcion: "Pega tu CV y la oferta: obtén un prompt que corrige estructura, redacción y palabras clave, y te devuelve cambios, brechas y datos a verificar.",
      resumen: "Mejora el CV que ya tienes: diagnóstico, versión optimizada, registro de cambios y brechas reales frente a la oferta, sin inventar experiencia.",
      queObtienes: "Un diagnóstico, tu CV optimizado en Word, el registro de cambios y las brechas reales frente a la oferta.",
      tipo: "pagina-propia",
      tiempo: "10–15 min",
      tiempoLectura: "22 min",
      etiquetas: ["Descarga en Word"],
      secciones: [
        { id: "como-funciona", titulo: "Cómo funciona la herramienta" },
        { id: "optimizar-o-crear", titulo: "¿Optimizar o crear un CV nuevo?" },
        { id: "diagnostico", titulo: "Diagnóstico en 9 problemas típicos" },
        { id: "priorizar", titulo: "Cómo priorizar según la oferta" },
        { id: "bullets", titulo: "5 patrones de bullets" },
        { id: "frases", titulo: "12 frases débiles transformadas" },
        { id: "palabras-clave", titulo: "Palabras clave sin falsear" },
        { id: "eliminar", titulo: "Qué eliminar de tu CV" },
        { id: "prompt", titulo: "Cómo está hecho el prompt" },
        { id: "ejemplo", titulo: "Ejemplo completo paso a paso" },
        { id: "revision", titulo: "Revisión final en 10 puntos" },
        { id: "entrevista", titulo: "Registro de cambios y entrevista" },
        { id: "limites", titulo: "Límites y verificación" },
        { id: "preguntas", titulo: "Preguntas frecuentes" },
      ],
    },
  },
  {
    slug: "preparar-entrevista-de-trabajo",
    categoria: "carrera-y-empleo",
    titulo: "Preparar una entrevista de trabajo con IA (simulador)",
    descripcionCorta: "Practica las preguntas más probables de tu entrevista y recibe una devolución sobre tus respuestas.",
    estado: "publicada",
    lote: 1,
    fechaPublicacion: "2026-09-26",
    fechaActualizacion: "2026-09-26",
    relacionadas: ["optimizar-cv", "crear-cv-ats-formato-harvard", "analizar-oferta-laboral", "calcular-salario-y-negociar-oferta"],
    pagina: {
      h1: "Prepara tu entrevista con un entrenamiento hecho a partir de tu CV y la oferta",
      tituloCorto: "Preparar una entrevista de trabajo con IA",
      metaTitulo: "Preparar una entrevista de trabajo con IA (simulador)",
      descripcion: "Convierte tu CV y la oferta en un entrenamiento: preguntas por categoría, qué evalúa cada una, simulación en vivo y cronómetro. Gratis, sin registro.",
      resumen: "Un plan de práctica hecho con tu CV y la oferta: banco de preguntas con su estructura de respuesta o simulación en vivo, cronómetro, grabadora e historias STAR.",
      queObtienes: "Tu hoja de estudio, preguntas probables con qué evalúa cada una, un cronómetro de 2 minutos, tu banco de historias STAR y la checklist del día previo.",
      tipo: "pagina-propia",
      tiempo: "30–60 min",
      tiempoLectura: "22 min",
      etiquetas: ["Simulación en vivo"],
      secciones: [
        { id: "como-funciona", titulo: "Cómo funciona la herramienta" },
        { id: "investigar", titulo: "Investigar la oferta y la empresa" },
        { id: "tipos", titulo: "Tipos de preguntas" },
        { id: "star", titulo: "Método STAR con 3 ejemplos" },
        { id: "proyecto", titulo: "Explicar un proyecto técnico" },
        { id: "fortalezas", titulo: "Fortalezas y áreas de mejora" },
        { id: "tecnologia", titulo: "Cuando no conoces una tecnología" },
        { id: "delicados", titulo: "Temas delicados" },
        { id: "contradicciones", titulo: "Detectar contradicciones" },
        { id: "ejercicios", titulo: "Ejercicios prácticos" },
        { id: "memorizar", titulo: "Practicar sin memorizar" },
        { id: "checklist", titulo: "Checklist 24 horas antes" },
        { id: "prompt", titulo: "Cómo está hecho el prompt" },
        { id: "ejemplo", titulo: "Ejemplo completo" },
        { id: "revision", titulo: "Lista de revisión" },
        { id: "limites", titulo: "Límites y verificación" },
        { id: "preguntas", titulo: "Preguntas frecuentes" },
      ],
    },
  },
  {
    slug: "analizar-oferta-laboral",
    categoria: "carrera-y-empleo",
    titulo: "Comparar tu CV con una oferta laboral por requisitos",
    descripcionCorta: "Compara tu CV con los requisitos de una oferta y ve qué cubres, qué te falta y qué destacar.",
    estado: "publicada",
    lote: 1,
    fechaPublicacion: "2026-09-26",
    fechaActualizacion: "2026-09-26",
    relacionadas: ["optimizar-cv", "preparar-entrevista-de-trabajo", "crear-cv-ats-formato-harvard", "crear-plan-de-busqueda-de-empleo"],
    pagina: {
      h1: "Analiza qué tan alineado está tu CV con una oferta laboral",
      tituloCorto: "Comparar tu CV con una oferta laboral",
      metaTitulo: "Comparar tu CV con una oferta laboral por requisitos",
      descripcion: "Compara tu CV con una oferta: tabla de requisitos con evidencia, palabras clave faltantes y un % orientativo explicado. Gratis, sin registro.",
      resumen: "Una tabla requisito por requisito con la evidencia de tu CV, palabras clave faltantes, un porcentaje orientativo con su fórmula y un semáforo para decidir si postular.",
      queObtienes: "La tabla de requisitos (exportable a CSV), el porcentaje orientativo recalculado con tus pesos, un semáforo de decisión y tu plan de acción.",
      tipo: "pagina-propia",
      tiempo: "10–15 min",
      tiempoLectura: "18 min",
      etiquetas: ["Exporta a CSV"],
      secciones: [
        { id: "como-funciona", titulo: "Cómo funciona la herramienta" },
        { id: "anatomia", titulo: "Anatomía de un anuncio" },
        { id: "lenguaje", titulo: "Obligatorios vs deseables" },
        { id: "palabras-clave", titulo: "Palabras clave y competencia" },
        { id: "estados", titulo: "Las 4 clasificaciones" },
        { id: "porcentaje", titulo: "Cómo se calcula el porcentaje" },
        { id: "ejemplo", titulo: "Ejemplo completo" },
        { id: "brechas", titulo: "Brechas: bloqueantes o salvables" },
        { id: "postular", titulo: "¿Postular sin cumplir el 100 %?" },
        { id: "accion", titulo: "Del análisis a la acción" },
        { id: "prompt", titulo: "Cómo está hecho el prompt" },
        { id: "revision", titulo: "Lista de revisión" },
        { id: "limites", titulo: "Límites y verificación" },
        { id: "preguntas", titulo: "Preguntas frecuentes" },
      ],
    },
  },
  {
    slug: "calcular-salario-y-negociar-oferta",
    categoria: "carrera-y-empleo",
    titulo: "Evaluar una oferta laboral y negociar tu salario con IA",
    descripcionCorta: "Evalúa una oferta laboral con números y prepara los argumentos para negociar tu salario.",
    estado: "publicada",
    lote: 2,
    fechaPublicacion: "2026-09-26",
    fechaActualizacion: "2026-09-26",
    relacionadas: ["preparar-entrevista-de-trabajo", "analizar-oferta-laboral", "crear-presupuesto-personal", "crear-plan-de-busqueda-de-empleo"],
    pagina: {
      h1: "Analiza tu oferta de trabajo y prepárate para negociar el salario",
      tituloCorto: "Evaluar una oferta y negociar tu salario",
      metaTitulo: "Evaluar una oferta laboral y negociar tu salario con IA",
      descripcion: "Calcula el valor anual de una oferta (fijo, variable, beneficios), define tus 3 cifras y prepara respuestas para negociar. Gratis, sin registro.",
      resumen: "Calcula el valor anual real de una oferta con fórmulas a la vista, define tu mínimo, objetivo y ancla con tus propias referencias y prepara respuestas honestas para negociar.",
      queObtienes: "El valor anual de la oferta (conservador y completo), una comparación de dos ofertas, tus tres cifras validadas y respuestas preparadas para copiar.",
      tipo: "pagina-propia",
      tiempo: "20–30 min",
      tiempoLectura: "22 min",
      etiquetas: ["Exporta a CSV"],
      secciones: [
        { id: "como-funciona", titulo: "Cómo funciona la herramienta" },
        { id: "bruto-neto", titulo: "Salario bruto vs neto" },
        { id: "variable", titulo: "Fijo, variable y bonos" },
        { id: "beneficios", titulo: "Beneficios: ponerles precio" },
        { id: "valor-anual", titulo: "Valor anual real" },
        { id: "tres-cifras", titulo: "Tus 3 cifras" },
        { id: "referencias", titulo: "Referencias salariales" },
        { id: "preguntas-reclutador", titulo: "Qué preguntar al reclutador" },
        { id: "expectativa", titulo: "Responder la expectativa salarial" },
        { id: "sin-mentir", titulo: "Negociar sin mentir" },
        { id: "ejemplo", titulo: "Ejemplo completo" },
        { id: "errores", titulo: "Errores y checklist" },
        { id: "prompt", titulo: "Cómo está hecho el prompt" },
        { id: "revision", titulo: "Lista de revisión" },
        { id: "limites", titulo: "Límites y verificación" },
        { id: "preguntas", titulo: "Preguntas frecuentes" },
      ],
    },
  },
  {
    slug: "crear-plan-de-busqueda-de-empleo",
    categoria: "carrera-y-empleo",
    titulo: "Plan de búsqueda de empleo con IA y control de postulaciones",
    descripcionCorta: "Ordena tu búsqueda de trabajo con un plan semanal según tus horas y un registro de tus postulaciones.",
    estado: "publicada",
    lote: 2,
    fechaPublicacion: "2026-09-26",
    fechaActualizacion: "2026-09-26",
    relacionadas: ["analizar-oferta-laboral", "crear-cv-ats-formato-harvard", "preparar-entrevista-de-trabajo", "optimizar-cv"],
    pagina: {
      h1: "Crea tu plan de búsqueda de empleo y mide qué está funcionando",
      tituloCorto: "Plan de búsqueda de empleo y registro de postulaciones",
      metaTitulo: "Plan de búsqueda de empleo con IA y control de postulaciones",
      descripcion: "Define tu puesto objetivo, obtén un plan semanal según tus horas y registra cada postulación para ver dónde falla tu búsqueda. Gratis, sin registro.",
      resumen: "Un plan de 4 semanas que cabe en tus horas reales, exportable a tu calendario, y un registro de postulaciones que calcula tu embudo y te avisa de los seguimientos.",
      queObtienes: "Tu objetivo en una frase, el calendario de 4 semanas con la suma de minutos comprobada, vacantes priorizadas, tres plantillas de mensajes y un tracker con embudo.",
      tipo: "pagina-propia",
      tiempo: "20–30 min",
      tiempoLectura: "20 min",
      etiquetas: ["Exporta a calendario y CSV"],
      secciones: [
        { id: "como-funciona", titulo: "Cómo funciona la herramienta" },
        { id: "objetivo", titulo: "Definir un puesto objetivo" },
        { id: "donde-buscar", titulo: "Dónde buscar ofertas" },
        { id: "matriz", titulo: "Matriz para elegir vacantes" },
        { id: "cv", titulo: "Adaptar el CV sin perder horas" },
        { id: "registro-columnas", titulo: "Qué columnas importan" },
        { id: "seguimiento", titulo: "Cuándo hacer seguimiento" },
        { id: "embudo", titulo: "Leer tu embudo" },
        { id: "rechazos", titulo: "Rechazos y entrevistas" },
        { id: "ejemplo", titulo: "Una semana completa" },
        { id: "plantillas", titulo: "Plantillas de mensajes" },
        { id: "prompt", titulo: "Cómo está hecho el prompt" },
        { id: "revision", titulo: "Lista de revisión" },
        { id: "limites", titulo: "Límites y verificación" },
        { id: "preguntas", titulo: "Preguntas frecuentes" },
      ],
    },
  },

  // ───────────── Viajes y entretenimiento ─────────────
  {
    slug: "planificar-presupuesto-de-viaje",
    categoria: "viajes-y-entretenimiento",
    titulo: "Calcular el presupuesto de un viaje: plantilla + IA",
    descripcionCorta: "Calcula cuánto costará tu viaje completo y qué margen te queda antes de reservar.",
    estado: "publicada",
    lote: 1,
    fechaPublicacion: "2026-09-26",
    fechaActualizacion: "2026-09-26",
    relacionadas: ["crear-itinerario-de-viaje", "comparar-opciones-de-viaje", "descubrir-destinos-segun-presupuesto", "crear-plan-de-ahorro"],
    pagina: {
      h1: "Calcula el presupuesto real de tu viaje antes de reservar",
      tituloCorto: "Calcular el presupuesto de un viaje",
      metaTitulo: "Presupuesto de viaje: calculadora y plantilla con IA",
      descripcion: "Organiza tu viaje por categorías, separa gastos conocidos, estimados y opcionales, suma imprevistos y compara 3 escenarios. Sin precios inventados.",
      resumen: "Ordena los gastos de tu viaje por categoría, calcula el costo por persona, el margen para imprevistos y tres escenarios, con los precios que tú encuentres.",
      queObtienes: "El total y el costo por persona, tres escenarios con gráfico, los gastos que olvidaste y tu tabla lista para Excel o para imprimir.",
      tipo: "pagina-propia",
      tiempo: "10–15 min",
      tiempoLectura: "20 min",
      etiquetas: ["Exporta a CSV"],
      secciones: [
        { id: "como-funciona", titulo: "Cómo funciona la herramienta" },
        { id: "siete-pasos", titulo: "Presupuesto de viaje en 7 pasos" },
        { id: "categorias", titulo: "Las categorías de gasto" },
        { id: "tipos-de-gasto", titulo: "Conocidos, estimados y opcionales" },
        { id: "olvidados", titulo: "Los 15 gastos que casi todos olvidan" },
        { id: "fijos-variables", titulo: "Gastos fijos vs variables" },
        { id: "imprevistos", titulo: "Cuánto reservar para imprevistos" },
        { id: "ejemplo", titulo: "Ejemplo numérico completo" },
        { id: "ahorro", titulo: "Cómo reducir costos" },
        { id: "extranjero", titulo: "Pagar en el extranjero" },
        { id: "prompt", titulo: "Cómo está hecho el prompt" },
        { id: "revision", titulo: "Lista de revisión" },
        { id: "limites", titulo: "Límites y verificación" },
        { id: "preguntas", titulo: "Preguntas frecuentes" },
      ],
    },
  },
  {
    slug: "crear-itinerario-de-viaje",
    categoria: "viajes-y-entretenimiento",
    titulo: "Crear un itinerario de viaje día por día con IA (realista)",
    descripcionCorta: "Arma un itinerario día por día con tiempos de traslado realistas y sin sobrecargar las jornadas.",
    estado: "publicada",
    lote: 1,
    fechaPublicacion: "2026-09-29",
    fechaActualizacion: "2026-09-29",
    relacionadas: ["planificar-presupuesto-de-viaje", "comparar-opciones-de-viaje", "descubrir-destinos-segun-presupuesto"],
    pagina: {
      h1: "Crea un itinerario de viaje realista, día por día",
      tituloCorto: "Crear un itinerario de viaje día por día",
      metaTitulo: "Crear un itinerario de viaje día por día con IA (realista)",
      descripcion: "Arma tu itinerario día por día con franjas horarias, agrupado por zonas, con imprescindibles y tiempo libre. Gratis, sin registro.",
      resumen: "Actividades agrupadas por zona, tiempos de traslado, descansos y planes B por día. Tus horarios y reservas se respetan tal cual.",
      queObtienes: "La línea de tiempo de cada día, sin horarios cruzados ni días sobrecargados, con enlaces a Google Maps, calendario exportable y planes B.",
      tipo: "pagina-propia",
      tiempo: "15–20 min",
      tiempoLectura: "18 min",
      etiquetas: ["Exporta a calendario y CSV"],
      secciones: [
        { id: "como-funciona", titulo: "Cómo funciona la herramienta" },
        { id: "zonas", titulo: "La regla de las zonas" },
        { id: "cuantas-actividades", titulo: "Cuántas actividades caben en un día" },
        { id: "traslados", titulo: "Tiempos de desplazamiento" },
        { id: "imprescindibles-opcionales", titulo: "Imprescindibles vs opcionales" },
        { id: "llegada-salida", titulo: "Días de llegada y salida" },
        { id: "plan-b", titulo: "Margen para imprevistos y plan B" },
        { id: "adaptar", titulo: "Adaptar el itinerario" },
        { id: "ejemplo", titulo: "Ejemplo completo" },
        { id: "verificar-horarios", titulo: "Verificar horarios y reservas" },
        { id: "prompt", titulo: "Cómo está hecho el prompt" },
        { id: "revision", titulo: "Lista de revisión" },
        { id: "limites", titulo: "Límites y verificación" },
        { id: "preguntas", titulo: "Preguntas frecuentes" },
      ],
    },
  },
  {
    slug: "encontrar-fechas-mas-baratas-para-volar",
    categoria: "viajes-y-entretenimiento",
    titulo: "Fechas más baratas para volar: compara ida y vuelta",
    descripcionCorta: "Compara combinaciones de fechas de ida y vuelta con los precios que tú consultas y elige la más conveniente.",
    estado: "publicada",
    lote: 2,
    fechaPublicacion: "2026-09-29",
    fechaActualizacion: "2026-09-29",
    relacionadas: ["planificar-presupuesto-de-viaje", "crear-itinerario-de-viaje", "comparar-opciones-de-viaje"],
    pagina: {
      h1: "Encuentra las fechas más baratas para volar dentro de tu período",
      tituloCorto: "Fechas más baratas para volar",
      metaTitulo: "Fechas más baratas para volar: compara ida y vuelta",
      descripcion: "Indica período y duración: generamos todas las combinaciones de ida y vuelta, te guiamos para obtener precios y las ordenamos de menor a mayor.",
      resumen: "Genera todas las combinaciones de fecha de tu período, te guía para obtener precios reales y las compara con una tabla ordenable y un mapa de calor.",
      queObtienes: "El número de combinaciones posibles, una tabla ordenable con la más barata resaltada, el ajuste por equipaje y traslados, y un mapa de calor por día y duración.",
      tipo: "pagina-propia",
      tiempo: "15–25 min",
      tiempoLectura: "20 min",
      etiquetas: ["Exporta a CSV"],
      secciones: [
        { id: "como-funciona", titulo: "Cómo funciona la herramienta" },
        { id: "flexibilidad", titulo: "La flexibilidad de fechas" },
        { id: "noches-dias", titulo: "Noches vs días" },
        { id: "por-que-cambian", titulo: "Por qué cambian los precios" },
        { id: "metodo", titulo: "Método paso a paso" },
        { id: "comparar-tarifas", titulo: "Cómo comparar tarifas" },
        { id: "alternativos", titulo: "Aeropuertos alternativos" },
        { id: "ejemplo", titulo: "Ejemplo práctico" },
        { id: "mitos", titulo: "Mitos sobre el mejor día" },
        { id: "verificar", titulo: "Verificar antes de comprar" },
        { id: "prompt", titulo: "Cómo está hecho el prompt" },
        { id: "revision", titulo: "Lista de revisión" },
        { id: "limites", titulo: "Límites y verificación" },
        { id: "preguntas", titulo: "Preguntas frecuentes" },
      ],
    },
  },
  {
    slug: "comparar-opciones-de-viaje",
    categoria: "viajes-y-entretenimiento",
    titulo: "Comparar opciones de viaje con criterios claros",
    descripcionCorta: "Compara varias opciones de viaje con los mismos criterios para decidir sin arrepentirte.",
    estado: "publicada",
    lote: 3,
    fechaPublicacion: "2026-09-29",
    fechaActualizacion: "2026-09-29",
    relacionadas: ["planificar-presupuesto-de-viaje", "crear-itinerario-de-viaje", "encontrar-fechas-mas-baratas-para-volar"],
    pagina: {
      h1: "Compara tus opciones de viaje más allá del precio",
      tituloCorto: "Comparar opciones de viaje",
      metaTitulo: "Comparar opciones de viaje con criterios claros",
      descripcion: "Compara destinos, hoteles, transportes o paquetes por costo total, tiempo, comodidad y tus prioridades, y mira cómo cambia la decisión.",
      resumen: "Arma una matriz de decisión con tus criterios y sus pesos, calcula el costo total ajustado de cada opción y compara cómo cambia el ganador según tus prioridades.",
      queObtienes: "Una matriz ponderada de hasta 5 opciones, el costo total ajustado de cada una (precio + extras + tu tiempo), y 3 escenarios de «si cambian tus prioridades».",
      tipo: "pagina-propia",
      tiempo: "10–20 min",
      tiempoLectura: "17 min",
      etiquetas: ["Exporta a CSV"],
      secciones: [
        { id: "como-funciona", titulo: "Cómo funciona la herramienta" },
        { id: "costo-total", titulo: "Por qué el precio inicial no es el costo total" },
        { id: "criterios", titulo: "Cómo elegir tus criterios y sus pesos" },
        { id: "datos-vs-valoraciones", titulo: "Datos objetivos vs. valoraciones" },
        { id: "tiempo-vs-dinero", titulo: "Tiempo vs. dinero" },
        { id: "revisar-alojamiento", titulo: "Qué revisar en un alojamiento" },
        { id: "revisar-transporte", titulo: "Qué revisar en un transporte" },
        { id: "costos-ocultos", titulo: "Costos ocultos más comunes" },
        { id: "ejemplo", titulo: "Ejemplo práctico" },
        { id: "prompt", titulo: "Cómo está hecho el prompt" },
        { id: "checklist", titulo: "Checklist antes de reservar" },
        { id: "limites", titulo: "Límites y verificación" },
        { id: "preguntas", titulo: "Preguntas frecuentes" },
      ],
    },
  },
  {
    slug: "descubrir-destinos-segun-presupuesto",
    categoria: "viajes-y-entretenimiento",
    titulo: "¿A dónde viajar con tu presupuesto? Destinos viables",
    descripcionCorta: "Descubre destinos que encajan con tu dinero, tus fechas y lo que quieres vivir.",
    estado: "publicada",
    lote: 2,
    fechaPublicacion: "2026-09-29",
    fechaActualizacion: "2026-09-29",
    relacionadas: ["encontrar-fechas-mas-baratas-para-volar", "planificar-presupuesto-de-viaje", "crear-itinerario-de-viaje"],
    pagina: {
      h1: "Descubre a qué destinos puedes viajar con tu presupuesto",
      tituloCorto: "¿A dónde viajar con tu presupuesto?",
      metaTitulo: "¿A dónde viajar con tu presupuesto? Destinos viables",
      descripcion: "Indica presupuesto total, origen, viajeros y días: te guiamos para encontrar destinos donde pasajes + alojamiento caben, y cuánto te queda para el resto.",
      resumen: "Reparte tu presupuesto en pasajes, alojamiento, gastos e imprevistos, y compara hasta 8 destinos candidatos con el costo total real recalculado por la página, nunca por la IA.",
      queObtienes: "El reparto de tu presupuesto con un donut, una tabla de destinos con su costo total recalculado, el dinero restante y las noches máximas viables de cada uno.",
      tipo: "pagina-propia",
      tiempo: "10–20 min",
      tiempoLectura: "19 min",
      etiquetas: ["Exporta a CSV"],
      secciones: [
        { id: "como-funciona", titulo: "Cómo funciona la herramienta" },
        { id: "reparto", titulo: "Cómo repartir un presupuesto de viaje" },
        { id: "costo-total", titulo: "Por qué un destino barato puede salir caro" },
        { id: "duracion", titulo: "Costos fijos vs. costos diarios" },
        { id: "flexibilidad", titulo: "Flexibilidad de fechas y de destino" },
        { id: "metodo", titulo: "Métodos para descubrir destinos" },
        { id: "ejemplo", titulo: "Ejemplo completo" },
        { id: "gastos", titulo: "Gastos que debes reservar" },
        { id: "prompt", titulo: "Cómo está hecho el prompt" },
        { id: "checklist", titulo: "Checklist antes de reservar" },
        { id: "limites", titulo: "Límites y verificación" },
        { id: "preguntas", titulo: "Preguntas frecuentes" },
      ],
    },
  },

  // ───────────── Emprendimiento ─────────────
  {
    slug: "crear-logo-profesional-para-mi-empresa",
    categoria: "emprendimiento",
    titulo: "Crear el logo de tu empresa con IA: brief, prompts y kit",
    descripcionCorta: "Define el brief de tu marca y obtén prompts y un kit de logo para trabajar con una IA de imágenes.",
    estado: "publicada",
    lote: 2,
    fechaPublicacion: "2026-09-30",
    fechaActualizacion: "2026-09-30",
    relacionadas: ["crear-catalogo-de-productos", "crear-propuesta-de-valor", "crear-landing-page-de-venta"],
    pagina: {
      h1: "Crea un logo profesional para tu negocio con IA, paso a paso",
      tituloCorto: "Crear el logo de tu empresa",
      metaTitulo: "Crear el logo de tu empresa con IA: brief, prompts y kit",
      descripcion: "Convierte los datos de tu negocio en una dirección creativa, prompts para generar tu logo y un kit: variantes, paleta, tipografías y favicon.",
      resumen: "Arma el brief de tu marca, 3 conceptos y sus prompts de imagen por variante, y prueba el resultado en un laboratorio local: fondos, tamaños pequeños, favicon y un kit descargable.",
      queObtienes: "Un brief con 3 conceptos, una paleta con su contraste WCAG ya calculado, tipografías gratuitas sugeridas, 8 prompts de imagen (uno por variante) y un laboratorio para probar tu logo antes de usarlo.",
      tipo: "pagina-propia",
      tiempo: "15–25 min",
      tiempoLectura: "21 min",
      etiquetas: ["Exporta a ZIP"],
      secciones: [
        { id: "como-funciona", titulo: "Cómo funciona la herramienta" },
        { id: "que-funciona", titulo: "Qué hace que un logo funcione" },
        { id: "tipos-de-logo", titulo: "Logotipo, isotipo, imagotipo e isologo" },
        { id: "brief-antes-que-imagen", titulo: "Por qué el brief va antes que la imagen" },
        { id: "colores", titulo: "Cómo elegir colores y comprobar contraste" },
        { id: "tipografias", titulo: "Cómo elegir tipografías y verificar su licencia" },
        { id: "tamano-pequeno", titulo: "La prueba del tamaño pequeño" },
        { id: "errores-frecuentes", titulo: "Errores frecuentes de los logos con IA" },
        { id: "vectorizar", titulo: "De la imagen de IA a un logo usable" },
        { id: "preparar-identidad", titulo: "Preparar la identidad para imprimir, web y redes" },
        { id: "registro-de-marca", titulo: "Registro de marca y derechos de uso" },
        { id: "ejemplo", titulo: "Ejemplo completo" },
        { id: "prompt", titulo: "Cómo está hecho el prompt" },
        { id: "checklist", titulo: "Checklist antes de usar tu logo" },
        { id: "limites", titulo: "Límites y verificación" },
        { id: "preguntas", titulo: "Preguntas frecuentes" },
      ],
    },
  },
  {
    slug: "crear-plan-de-negocio",
    categoria: "emprendimiento",
    titulo: "Cómo hacer un plan de negocio con IA (ejemplo y Word)",
    descripcionCorta: "Ordena tu idea en un plan de negocio claro, con tus cifras y un documento en Word para presentar.",
    estado: "publicada",
    lote: 1,
    fechaPublicacion: "2026-09-30",
    fechaActualizacion: "2026-09-30",
    relacionadas: ["calcular-rentabilidad-de-mi-negocio", "identificar-nichos-de-mercado"],
    pagina: {
      h1: "Crea un plan de negocio con IA: inversión, margen y punto de equilibrio calculados",
      tituloCorto: "Crear un plan de negocio",
      metaTitulo: "Cómo hacer un plan de negocio con IA (ejemplo y Word)",
      descripcion: "Convierte tu idea en un plan de negocio con inversión, costos, margen y punto de equilibrio calculados, y un Word descargable.",
      resumen: "Cuenta tu negocio y tus números, copia un prompt en 2 fases y arma un plan de negocio completo, con cada cifra identificada como dato, cálculo o supuesto.",
      queObtienes: "Un plan de 19 secciones con tu inversión, tus costos, tu margen y tu punto de equilibrio ya calculados, listo para descargar en Word.",
      tipo: "pagina-propia",
      tiempo: "15–25 min",
      tiempoLectura: "16 min",
      etiquetas: ["Exporta a Word", "Guarda tu proyecto"],
      secciones: [
        { id: "como-funciona", titulo: "Cómo funciona la herramienta" },
        { id: "para-que-sirve", titulo: "Para qué sirve un plan de negocio" },
        { id: "numeros-que-necesitas", titulo: "Los números que necesitas" },
        { id: "margen-y-equilibrio", titulo: "Cómo se calculan el margen y el punto de equilibrio" },
        { id: "dos-fases", titulo: "Las 2 fases del prompt" },
        { id: "dato-calculo-supuesto", titulo: "Dato, cálculo y supuesto" },
        { id: "errores-frecuentes", titulo: "Errores frecuentes con IA" },
        { id: "ejemplo", titulo: "Ejemplo completo" },
        { id: "prompt", titulo: "Cómo está hecho el prompt" },
        { id: "checklist", titulo: "Checklist antes de presentar tu plan" },
        { id: "limites", titulo: "Límites y verificación" },
        { id: "preguntas", titulo: "Preguntas frecuentes" },
      ],
    },
  },
  {
    slug: "calcular-rentabilidad-de-mi-negocio",
    categoria: "emprendimiento",
    titulo: "Calcular la rentabilidad de tu negocio por producto",
    descripcionCorta: "Descubre cuánto gana tu negocio por producto y dónde se te va el margen.",
    estado: "publicada",
    lote: 1,
    fechaPublicacion: "2026-09-30",
    fechaActualizacion: "2026-09-30",
    relacionadas: ["crear-plan-de-negocio", "calcular-precio-de-venta"],
    pagina: {
      h1: "Calcula cuánto gana realmente tu negocio",
      tituloCorto: "Calcular la rentabilidad de tu negocio",
      metaTitulo: "Calcular la rentabilidad de tu negocio por producto",
      descripcion: "Descubre cuánto gana tu negocio: utilidad bruta y operativa, margen por producto, punto de equilibrio y escenarios.",
      resumen: "Carga tus productos y tus costos, y esta página calcula tu margen, tu punto de equilibrio y la sensibilidad de tu resultado; la IA lo interpreta y te sugiere acciones.",
      queObtienes: "Tu utilidad bruta y operativa, la rentabilidad por producto, tu punto de equilibrio, un tornado de sensibilidad ±10 % y un informe descargable en .csv.",
      tipo: "pagina-propia",
      tiempo: "10–20 min",
      tiempoLectura: "18 min",
      etiquetas: ["Importa CSV", "Exporta informe"],
      secciones: [
        { id: "como-funciona", titulo: "Cómo funciona la herramienta" },
        { id: "ingresos-utilidad-flujo", titulo: "Ingresos, utilidad y flujo de caja" },
        { id: "fijos-vs-variables", titulo: "Costos fijos vs variables" },
        { id: "costo-real-producto", titulo: "Cómo calcular el costo real de un producto" },
        { id: "margenes", titulo: "Margen bruto, operativo y neto" },
        { id: "markup-vs-margen", titulo: "Markup vs margen" },
        { id: "contribucion-y-equilibrio", titulo: "Margen de contribución y punto de equilibrio" },
        { id: "caso-completo", titulo: "Caso completo: una pastelería" },
        { id: "variables-que-mueven", titulo: "Qué variables mueven más tu resultado" },
        { id: "errores-frecuentes", titulo: "Errores frecuentes al medir la rentabilidad" },
        { id: "cuando-contador", titulo: "Cuándo acudir a un contador" },
        { id: "prompt", titulo: "Cómo está hecho el prompt" },
        { id: "checklist", titulo: "Checklist antes de decidir" },
        { id: "limites", titulo: "Límites y verificación" },
        { id: "preguntas", titulo: "Preguntas frecuentes" },
      ],
    },
  },
  {
    slug: "identificar-nichos-de-mercado",
    categoria: "emprendimiento",
    titulo: "Cómo encontrar y validar un nicho de mercado (con IA)",
    descripcionCorta: "Encuentra nichos posibles y valida cuál merece tu primera inversión con pruebas baratas.",
    estado: "publicada",
    lote: 2,
    fechaPublicacion: "2026-09-30",
    fechaActualizacion: "2026-09-30",
    relacionadas: ["crear-plan-de-negocio", "crear-propuesta-de-valor"],
    pagina: {
      h1: "Encuentra nichos de mercado que encajen contigo y valídalos antes de invertir",
      tituloCorto: "Identificar un nicho de mercado",
      metaTitulo: "Cómo encontrar y validar un nicho de mercado (con IA)",
      descripcion: "Transforma tus conocimientos y recursos en nichos concretos, compáralos con criterios explícitos y valídalos con un plan de 14 días.",
      resumen: "Cuenta tu inventario personal, la IA propone entre 8 y 10 nichos como hipótesis, y esta página los compara en una matriz con tus propios pesos antes de armar un plan de validación de 14 días.",
      queObtienes: "De 8 a 10 nichos con ficha completa, una matriz de comparación con pesos editables, un plan de validación de 14 días para tus 2 favoritos y un registro de entrevistas en tu navegador.",
      tipo: "pagina-propia",
      tiempo: "20–30 min",
      tiempoLectura: "18 min",
      etiquetas: ["Matriz con pesos editables", "Registro de validación"],
      secciones: [
        { id: "como-funciona", titulo: "Cómo funciona la herramienta" },
        { id: "que-es-un-nicho", titulo: "Qué es realmente un nicho" },
        { id: "mercado-vs-nicho", titulo: "Mercado vs nicho: de amplio a específico" },
        { id: "problemas-que-pagan", titulo: "Problemas por los que la gente paga" },
        { id: "mercado-amplio", titulo: "Señales de un mercado demasiado amplio" },
        { id: "evaluar-competencia", titulo: "Evaluar la competencia sin herramientas de pago" },
        { id: "criterios-matriz", titulo: "Criterios para comparar nichos" },
        { id: "validar-antes-de-invertir", titulo: "Validar antes de invertir" },
        { id: "entrevistas", titulo: "Entrevistas que no te mientan" },
        { id: "nicho-a-oferta", titulo: "De nicho a oferta concreta" },
        { id: "ejercicios", titulo: "Ejercicios prácticos" },
        { id: "ejemplo", titulo: "Ejemplo completo" },
        { id: "prompt", titulo: "Cómo están hechos los 2 prompts" },
        { id: "checklist", titulo: "Checklist antes de validar" },
        { id: "limites", titulo: "Límites y verificación" },
        { id: "preguntas", titulo: "Preguntas frecuentes" },
      ],
    },
  },
  {
    slug: "crear-catalogo-de-productos",
    categoria: "emprendimiento",
    titulo: "Crear un catálogo de productos PDF y para WhatsApp con IA",
    descripcionCorta: "Convierte tus productos en un catálogo en PDF y en un formato listo para compartir por WhatsApp.",
    estado: "publicada",
    lote: 2,
    fechaPublicacion: "2026-09-30",
    fechaActualizacion: "2026-09-30",
    relacionadas: ["crear-logo-profesional-para-mi-empresa", "crear-publicaciones-para-redes-sociales"],
    pagina: {
      h1: "Crea un catálogo de productos con IA: organizado, con precios verificados",
      tituloCorto: "Crear un catálogo de productos",
      metaTitulo: "Crear un catálogo de productos con IA (PDF y WhatsApp)",
      descripcion: "Convierte tu lista de productos en un catálogo organizado por categorías, con fichas para redes y un enlace de WhatsApp por producto.",
      resumen: "Escribe o importa tus productos, copia un prompt y esta página organiza tu catálogo, verificando que el precio de cada producto sea exactamente el que escribiste.",
      queObtienes: "Un catálogo agrupado en hasta 8 categorías, fichas PNG para redes, un enlace de WhatsApp por producto, y un PDF y un .csv descargables, con el precio de cada producto verificado antes de dejarte descargar nada.",
      tipo: "pagina-propia",
      tiempo: "15–25 min",
      tiempoLectura: "17 min",
      etiquetas: ["Importa CSV", "Bloquea precios que no coinciden"],
      secciones: [
        { id: "como-funciona", titulo: "Cómo funciona la herramienta" },
        { id: "por-que-catalogo", titulo: "Por qué un catálogo ordenado vende más" },
        { id: "que-necesitas", titulo: "Qué necesitas antes de empezar" },
        { id: "categorias", titulo: "Organizar tus productos en categorías" },
        { id: "fichas-de-producto", titulo: "Qué hace buena una ficha de producto" },
        { id: "precios-y-bloqueo", titulo: "Precios, promociones y el bloqueo de descarga" },
        { id: "fotos-con-celular", titulo: "Fotografiar tus productos con el celular" },
        { id: "plantillas", titulo: "Elegir una plantilla según tu rubro" },
        { id: "whatsapp", titulo: "El enlace de WhatsApp" },
        { id: "formatos", titulo: "PDF, fichas para redes y .csv" },
        { id: "errores-frecuentes", titulo: "Errores frecuentes con IA" },
        { id: "mantener-actualizado", titulo: "Mantener tu catálogo actualizado" },
        { id: "ejemplo", titulo: "Ejemplo completo" },
        { id: "prompt", titulo: "Cómo está hecho el prompt" },
        { id: "checklist", titulo: "Checklist antes de publicar" },
        { id: "limites", titulo: "Límites y verificación" },
        { id: "preguntas", titulo: "Preguntas frecuentes" },
      ],
    },
  },

  // ───────────── Analítica e información ─────────────
  {
    slug: "analizar-ventas-con-excel",
    categoria: "analitica-e-informacion",
    titulo: "Analizar ventas en Excel con IA: dashboard, KPIs y hallazgos",
    descripcionCorta: "Convierte tu hoja de ventas en un tablero con indicadores clave y hallazgos que puedes accionar.",
    estado: "publicada",
    lote: 2,
    fechaPublicacion: "2026-09-30",
    fechaActualizacion: "2026-09-30",
    relacionadas: ["analizar-excel-con-ia", "limpiar-datos", "convertir-datos-en-graficos"],
    pagina: {
      h1: "Analiza tu archivo de ventas y entiende qué está pasando en tu negocio",
      tituloCorto: "Analizar ventas en Excel",
      metaTitulo: "Analizar ventas en Excel con IA: dashboard, KPIs y hallazgos",
      descripcion: "Sube tu Excel o CSV de ventas: obtén ventas totales, ticket promedio, evolución, productos clave y variaciones, con hechos separados de hipótesis.",
      resumen: "Sube tu archivo de ventas, esta página arma un dashboard inmediato en tu navegador (ventas, ticket promedio, evolución, top productos) y un prompt que guía a tu IA para un análisis riguroso, con hechos separados de hipótesis.",
      queObtienes: "Un dashboard con tus ventas, tu ticket promedio, tu evolución mensual y tus productos principales, la descomposición de la variación entre 2 períodos, y un informe descargable en PDF o en .csv.",
      tipo: "pagina-propia",
      tiempo: "10–20 min",
      tiempoLectura: "16 min",
      etiquetas: ["Lee Excel y CSV", "Nunca sube tu archivo a un servidor"],
      secciones: [
        { id: "como-funciona", titulo: "Cómo funciona la herramienta" },
        { id: "columnas-minimas", titulo: "Cómo preparar tu archivo de ventas" },
        { id: "facturacion-ticket", titulo: "Facturación, unidades y ticket promedio" },
        { id: "comparar-periodos", titulo: "Cómo comparar períodos correctamente" },
        { id: "descomponer-variacion", titulo: "Descomponer una variación" },
        { id: "patrones-productos", titulo: "Productos que requieren atención" },
        { id: "tendencia-no-es-causalidad", titulo: "Tendencia no es causalidad" },
        { id: "calidad-de-datos", titulo: "Calidad de datos: qué revisa esta página" },
        { id: "privacidad", titulo: "Privacidad: qué se envía y qué no" },
        { id: "ejemplo", titulo: "Ejemplo completo" },
        { id: "prompt", titulo: "Cómo está hecho el prompt" },
        { id: "checklist", titulo: "Checklist antes de actuar sobre tus datos" },
        { id: "limites", titulo: "Límites y verificación" },
        { id: "preguntas", titulo: "Preguntas frecuentes" },
      ],
    },
  },
  {
    slug: "convertir-datos-en-graficos",
    categoria: "analitica-e-informacion",
    titulo: "Convertir datos en gráficos: elige el gráfico correcto",
    descripcionCorta: "Elige el gráfico correcto para cada dato y construye visualizaciones claras.",
    estado: "publicada",
    lote: 3,
    fechaPublicacion: "2026-09-30",
    fechaActualizacion: "2026-09-30",
    relacionadas: ["analizar-excel-con-ia", "analizar-ventas-con-excel", "limpiar-datos"],
    pagina: {
      h1: "Convierte tu tabla en gráficos claros y correctos",
      tituloCorto: "Convertir datos en gráficos",
      metaTitulo: "Convertir datos en gráficos: elige el gráfico correcto",
      descripcion: "Pega tu tabla o sube un Excel: te sugerimos el gráfico adecuado para cada pregunta, lo generamos al instante y te explicamos qué muestra y qué no.",
      resumen: "Dinos qué quieres responder y te proponemos el gráfico adecuado, generado en tu navegador, con títulos, unidades y sin ejes truncados.",
      queObtienes: "Un gráfico local inmediato según tu objetivo, entre 3 y 6 gráficos sugeridos por tu IA (dibujados con tus datos reales, nunca con los que calcule la IA), una galería comparativa y un informe descargable en PDF.",
      tipo: "pagina-propia",
      tiempo: "10–15 min",
      tiempoLectura: "15 min",
      etiquetas: ["Pega o sube tu tabla", "Nunca trunca el eje Y"],
      secciones: [
        { id: "como-funciona", titulo: "Cómo funciona la herramienta" },
        { id: "empieza-por-la-pregunta", titulo: "Empieza por la pregunta, no por el gráfico" },
        { id: "guia-rapida", titulo: "Guía rápida: comparar, evolucionar, componer, distribuir, relacionar" },
        { id: "barras-lineas-areas", titulo: "Barras vs líneas vs áreas" },
        { id: "dispersion-histogramas", titulo: "Dispersión e histogramas" },
        { id: "graficos-que-enganan", titulo: "Gráficos que engañan: 7 errores comunes" },
        { id: "muchos-datos", titulo: "Muchos datos: agregación, top N, small multiples" },
        { id: "titulos-que-comunican", titulo: "Títulos que comunican el hallazgo" },
        { id: "ejemplo", titulo: "Ejemplo: una misma tabla en 4 gráficos" },
        { id: "correlacion-no-es-causalidad", titulo: "Correlación visual no es causalidad" },
        { id: "prompt", titulo: "Cómo está hecho el prompt" },
        { id: "checklist", titulo: "Checklist antes de compartir un gráfico" },
        { id: "limites", titulo: "Límites y verificación" },
        { id: "preguntas", titulo: "Preguntas frecuentes" },
      ],
    },
  },
  {
    slug: "segmentar-clientes",
    categoria: "analitica-e-informacion",
    titulo: "Segmentar clientes con RFM en Excel (paso a paso con IA)",
    descripcionCorta: "Agrupa a tus clientes con el método RFM en Excel y decide a quién dirigirte primero.",
    estado: "publicada",
    lote: 3,
    fechaPublicacion: "2026-09-30",
    fechaActualizacion: "2026-09-30",
    relacionadas: ["analizar-ventas-con-excel", "crear-campana-publicitaria", "crear-estrategia-para-conseguir-clientes"],
    pagina: {
      h1: "Segmenta tu base de clientes con criterios claros",
      tituloCorto: "Segmentar clientes",
      metaTitulo: "Segmentar clientes con RFM en Excel (paso a paso con IA)",
      descripcion: "Divide tu base de clientes por recencia, frecuencia y valor (RFM) o criterios propios: tamaño, perfil y usos de cada segmento, bien explicados.",
      resumen: "Sube tu archivo de clientes o de ventas: esta página calcula los segmentos con RFM o con tus propias reglas, en tu navegador, y un prompt guía a tu IA para interpretarlos sin inventar nada.",
      queObtienes: "Una tabla de segmentos con su tamaño, su peso en los ingresos y sus métricas medias; un mapa de calor de recencia y frecuencia; una lista de clientes por segmento exportable a .csv; y un informe interpretado por tu IA, descargable en PDF.",
      tipo: "pagina-propia",
      tiempo: "10–15 min",
      tiempoLectura: "16 min",
      etiquetas: ["RFM o reglas propias", "Nunca envía un ID de cliente a la IA"],
      secciones: [
        { id: "como-funciona", titulo: "Cómo funciona la herramienta" },
        { id: "que-es-segmentar", titulo: "Qué es segmentar (y por qué no es lo mismo que etiquetar clientes)" },
        { id: "variables", titulo: "Qué variables sirven para segmentar" },
        { id: "rfm-explicado", titulo: "RFM explicado: recencia, frecuencia y valor monetario" },
        { id: "rfm-en-excel", titulo: "Cómo calcular RFM en Excel paso a paso" },
        { id: "nombres-segmentos", titulo: "Nombres y lectura de segmentos RFM" },
        { id: "segmentos-chicos", titulo: "Segmentos demasiado pequeños o inútiles: cómo evitarlos" },
        { id: "trato-distinto", titulo: "Por qué cada segmento necesita un trato distinto" },
        { id: "ejemplo", titulo: "Ejemplo práctico: 500 clientes ficticios de una tienda online" },
        { id: "privacidad", titulo: "Privacidad y uso responsable de datos de clientes" },
        { id: "prompt", titulo: "Cómo está hecho el prompt" },
        { id: "checklist", titulo: "Checklist antes de actuar sobre tus segmentos" },
        { id: "limites", titulo: "Límites y verificación" },
        { id: "preguntas", titulo: "Preguntas frecuentes" },
      ],
    },
  },
  { slug: "analizar-excel-con-ia", categoria: "analitica-e-informacion", titulo: "Analizar cualquier Excel con IA: hallazgos y gráficos", descripcionCorta: "Analiza cualquier hoja de Excel y obtén hallazgos y gráficos, separando los hechos de las hipótesis.", estado: "pendiente", lote: 1, relacionadas: ["limpiar-datos", "convertir-datos-en-graficos"] },
  { slug: "limpiar-datos", categoria: "analitica-e-informacion", titulo: "Limpiar datos en Excel con IA y registro de cambios", descripcionCorta: "Deja tus datos ordenados y consistentes, con un registro de cada cambio para poder revertirlo.", estado: "pendiente", lote: 2, relacionadas: ["analizar-excel-con-ia", "analizar-ventas-con-excel"] },

  // ───────────── Finanzas y economía ─────────────
  { slug: "crear-presupuesto-personal", categoria: "finanzas-y-economia", titulo: "Crear tu presupuesto personal mensual (calculadora + IA)", descripcionCorta: "Arma tu presupuesto mensual y descubre cuánto te sobra o te falta cada mes.", estado: "pendiente", lote: 1, relacionadas: ["crear-plan-de-ahorro", "calcular-interes-compuesto"] },
  { slug: "crear-plan-de-ahorro", categoria: "finanzas-y-economia", titulo: "Plan de ahorro: calcula cuánto ahorrar al mes para tu meta", descripcionCorta: "Calcula cuánto ahorrar cada mes para llegar a tu meta en la fecha que quieres.", estado: "pendiente", lote: 2, relacionadas: ["crear-presupuesto-personal", "calcular-interes-compuesto"] },
  { slug: "analizar-gastos-de-mi-negocio", categoria: "finanzas-y-economia", titulo: "Analizar los gastos de tu negocio: dónde se va el dinero", descripcionCorta: "Clasifica los gastos de tu negocio y encuentra los que puedes recortar sin afectar tus ventas.", estado: "pendiente", lote: 3, relacionadas: ["calcular-rentabilidad-de-mi-negocio", "calcular-punto-de-equilibrio"] },
  { slug: "calcular-precio-de-venta", categoria: "finanzas-y-economia", titulo: "Calcular el precio de venta con margen o markup", descripcionCorta: "Calcula el precio de venta que cubre tus costos y deja el margen que buscas.", estado: "pendiente", lote: 1, relacionadas: ["calcular-punto-de-equilibrio", "calcular-rentabilidad-de-mi-negocio"] },
  { slug: "calcular-interes-compuesto", categoria: "finanzas-y-economia", titulo: "Calculadora de interés compuesto con aportes mensuales", descripcionCorta: "Proyecta cómo crece un monto con aportes mensuales y una tasa que tú defines.", estado: "pendiente", lote: 1, relacionadas: ["crear-plan-de-ahorro", "crear-presupuesto-personal"] },
  { slug: "calcular-punto-de-equilibrio", categoria: "finanzas-y-economia", titulo: "Calcular el punto de equilibrio en unidades y dinero", descripcionCorta: "Averigua cuántas unidades y cuánto dinero necesitas vender para no perder.", estado: "pendiente", lote: 1, relacionadas: ["calcular-precio-de-venta", "analizar-gastos-de-mi-negocio"] },

  // ───────────── Marketing y ventas ─────────────
  { slug: "crear-calendario-de-contenidos", categoria: "marketing-y-ventas", titulo: "Crear un calendario de contenidos con IA (editable)", descripcionCorta: "Organiza qué publicar y cuándo en un calendario editable que puedes seguir semana a semana.", estado: "pendiente", lote: 2, relacionadas: ["crear-publicaciones-para-redes-sociales", "crear-plan-de-marketing"] },
  { slug: "crear-publicaciones-para-redes-sociales", categoria: "marketing-y-ventas", titulo: "Crear publicaciones para redes sociales con IA", descripcionCorta: "Escribe publicaciones para tus redes con tu tono y tu oferta, sin datos inventados.", estado: "pendiente", lote: 2, relacionadas: ["crear-calendario-de-contenidos", "crear-propuesta-de-valor"] },
  { slug: "crear-plan-de-marketing", categoria: "marketing-y-ventas", titulo: "Cómo hacer un plan de marketing práctico (ejemplo + IA)", descripcionCorta: "Arma un plan de marketing simple: a quién le hablas, por qué canal, con qué mensaje y cómo lo medirás.", estado: "pendiente", lote: 1, relacionadas: ["crear-propuesta-de-valor", "crear-calendario-de-contenidos"] },
  { slug: "crear-propuesta-de-valor", categoria: "marketing-y-ventas", titulo: "Cómo crear una propuesta de valor clara (ejemplos + IA)", descripcionCorta: "Explica en una frase qué ofreces, a quién y por qué te eligen, con ejemplos para inspirarte.", estado: "pendiente", lote: 2, relacionadas: ["crear-plan-de-marketing", "crear-landing-page-de-venta"] },
  { slug: "crear-campana-publicitaria", categoria: "marketing-y-ventas", titulo: "Crear una campaña publicitaria completa con IA", descripcionCorta: "Prepara una campaña de anuncios completa: objetivo, público, textos, presupuesto y qué medir.", estado: "pendiente", lote: 3, relacionadas: ["crear-plan-de-marketing", "crear-landing-page-de-venta"] },
  { slug: "crear-landing-page-de-venta", categoria: "marketing-y-ventas", titulo: "Crear una landing page de venta: estructura y textos con IA", descripcionCorta: "Define la estructura y los textos de una página de venta que explique tu oferta con claridad.", estado: "pendiente", lote: 3, relacionadas: ["crear-propuesta-de-valor", "crear-campana-publicitaria"] },
  { slug: "crear-estrategia-para-conseguir-clientes", categoria: "marketing-y-ventas", titulo: "Cómo conseguir clientes: crea tu sistema de captación con IA", descripcionCorta: "Diseña un sistema simple para captar clientes: de dónde vienen, cómo los atiendes y cómo les das seguimiento.", estado: "pendiente", lote: 2, relacionadas: ["crear-plan-de-marketing", "segmentar-clientes"] },
];
